#!/data/data/com.termux/files/usr/bin/bash

COLOR="#000000"
POINT_SIZE=250

VALID_ARGS=$(getopt -o f:g:o:s:t: --long font:,gradient:,output:,size:,text: -- "$@")
if [[ $? -ne 0 ]]; then
  printf "Unable to parse parameters\n"
  exit 1;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
  case "$1" in
    -f | --font)
      font=$2
      printf "font = $font\n"
      shift 2
      ;;

    -g | --gradient)
      gradient_colors=$2
      grad_left=${gradient_colors%%:*}
      grad_right=${gradient_colors##*:}
      printf "grad_left = $grad_left\n"
      printf "grad_right = $grad_right\n"
      shift 2
      ;;
	
    -o | --output)
      output=$2
      printf "output = $output\n"
      shift 2
      ;;

    -s | --size)
      point_size=$2
      printf "point_size = $point_size\n"
      shift 2
      ;;

    -t | --text)
      text=$2
      printf "text = $text\n"
      shift 2
      ;;

    --) shift; 
      break 
      ;;
  esac
done

#exit

if [[ -n $grad_left && -n $grad_right ]]; then
    convert -pointsize ${point_size:=$POINT_SIZE} -font $font -background none label:"$text"	\
	\( +clone -sparse-color Barycentric "0,%h $grad_left %w,0 $grad_right" \) -compose In -composite		\
	$output
else
    convert -pointsize ${point_size:=$POINT_SIZE} -font $font -background none label:"$text" $output
fi

