#!/bin/bash

BITRATE=192

function encode_to_opus()
{
#    opusenc --bitrate $BITRATE "$1" "${1%.*}.opus"
    ffmpeg -i "$1" -c:a libopus -b:a 192K "${1%.*}.opus"
}

if [[ $# > 0 ]]; then
    for f in "$@"; do
	encode_to_opus "$f"
    done
else
    for f in *; do
	encode_to_opus "$f"
    done
fi
